spring.application.name=ResumeForge AI Backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt-secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGIN:https://resumeforgeai.site,https://www.resumeforgeai.site}

app.razorpay.key-id=${RAZORPAY_KEY_ID}
app.razorpay.key-secret=${RAZORPAY_KEY_SECRET}
app.razorpay.payment-link=${RAZORPAY_PAYMENT_LINK}
app.razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}

app.resend.api-key=${RESEND_API_KEY}
app.mail.from-email=${MAIL_FROM_EMAIL:support@resumeforgeai.site}
app.mail.from-name=${MAIL_FROM_NAME:ResumeForge AI}
app.contact.receiver-email=${CONTACT_RECEIVER_EMAIL}

server.error.include-message=never
server.error.include-binding-errors=never